### ISSUE TITLE
Issue while executing a policy that was working on 0.8.23.1 version

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1170]
**Policy that am running**

```
policies:
  - name: lamb
    resource: lambda
    filters:
      - type: value
        key: Runtime
        value: "nodejs"
        op: eq
```

> 2017-05-15 23:01:19,189: custodian.output:ERROR Error while executing policy
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 261, in run
>     resources = self.policy.resource_manager.resources()
>   File "/usr/local/lib/python2.7/dist-packages/c7n/query.py", line 288, in resources
>     resources = self.augment(self.source.resources(query))
>   File "/usr/local/lib/python2.7/dist-packages/c7n/resources/awslambda.py", line 55, in augment
>     self.log))
>   File "/usr/local/lib/python2.7/dist-packages/c7n/resources/awslambda.py", line 78, in _lambda_function_tags
>     return list(w.map(process_tags, functions))
>   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 581, in result_iterator
>     yield future.result()
>   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
>     return self.__get_result()
>   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/c7n/resources/awslambda.py", line 67, in process_tags
>     tag_dict = retry(client.list_tags, Resource=arn)['Tags']
> AttributeError: 'Lambda' object has no attribute 'list_tags'
> 2017-05-15 23:01:19,189: custodian.commands:ERROR Error while executing policy lamb, continuing
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/c7n/commands.py", line 195, in run
>     policy()
>   File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 624, in __call__
>     return mode.run()
>   File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 261, in run
>     resources = self.policy.resource_manager.resources()
>   File "/usr/local/lib/python2.7/dist-packages/c7n/query.py", line 288, in resources
>     resources = self.augment(self.source.resources(query))
>   File "/usr/local/lib/python2.7/dist-packages/c7n/resources/awslambda.py", line 55, in augment
>     self.log))
>   File "/usr/local/lib/python2.7/dist-packages/c7n/resources/awslambda.py", line 78, in _lambda_function_tags
>     return list(w.map(process_tags, functions))
>   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 581, in result_iterator
>     yield future.result()
>   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
>     return self.__get_result()
>   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/c7n/resources/awslambda.py", line 67, in process_tags
>     tag_dict = retry(client.list_tags, Resource=arn)['Tags']
> AttributeError: 'Lambda' object has no attribute 'list_tags'

**Comment by kumarsiyer** [comment]
I am running as a assume role, which has only readonly IAM policy. The same policy works on **0.8.24.1** version while running with `--profile`

**Comment by kumarsiyer** [comment]
confirmed, after downgrading to **0.8.23.2** and this policy worked fine

**Comment by alfredgamulo** [comment]
Hi @kumarsiyer, 
Have you upgraded botocore to be >=1.5.43 for lambda tags?

**Comment by kumarsiyer** [comment]
thanks @alfredgamulo that was it. Missed the comments in [requirements.txt](https://github.com/capitalone/cloud-custodian/blob/master/requirements.txt) file

**Comment by kumarsiyer** [comment]
closing the issue.
